In [1]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
rev=arr[::-1]
print(rev)

[5 4 6 3 2 1]


In [2]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comparison = arr1 == arr2
print(comparison)

[[ True  True]
 [ True  True]]


In [4]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)

print("Most frequent value:", most_frequent)
print("Indices:", indices)

Most frequent value: 1
Indices: (array([0, 5, 7, 8, 9]),)


In [5]:
import numpy as np
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
values,counts=np.unique(x,return_counts=True)
most_freq=values[np.argmax(counts)]
indices=np.where(x==most_freq)

print("Most frequent value:", most_frequent)
print("Indices:", indices)

Most frequent value: 1
Indices: (array([0, 5, 7, 8, 9]),)


In [9]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
add=np.sum(gfg)
print(add)

45


In [10]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
row_add=gfg.sum(axis=1)
print(row_add)

[[14]
 [16]
 [15]]


In [11]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
col_add=gfg.sum(axis=0)
print(col_add)


[[20  9 16]]
